name: ai-azure-c1
dependencies:
  - python=3.8
  - azure-common==1.1.27
  - azure-storage-blob==12.8.1
  - conda==4.9.2
  - conda-build==3.18.11
  - conda-package-handling
  - conda-verify==3.4.2
  - imageio
  - imagesize==1.2.0
  - json5==0.9.5
  - jupyter==1.0.0
  - jupyterlab==2.1.5
  - notebook==6.0.3
  - numpy==1.18.5
  - pandas
  - Pillow==8.4
  - pkginfo==1.5.0.1
  - python-dateutil==2.8.1
  - python-dotenv==0.15.0
  - PyYAML==5.3.1
  - scikit-image==0.16.2
  - scikit-learn
  - scipy
  - seaborn==0.10.1
  - urllib3==1.25.9
  - pip:
      - azure-ai-formrecognizer==3.1.1
      - azure-cognitiveservices-vision-computervision==0.9.0
      - azure-cognitiveservices-vision-customvision==3.1.0
      - azure-cognitiveservices-vision-face==0.5.0
      - azure-core==1.15.0
      - jupyter-client
      - jupyter-console==6.1.0
      - jupyter-core==4.6.3
      - jupyterlab-server
      - video-indexer==0.1.8
